### ISSUE TITLE
Obrigado Rafael, mas não estou conseguindo instalar no xamp da erro 104

### ISSUE THREAD

**Issue by Ironaldo-Silva** [rafaelmarques/os#1]
estou tentando instalar via localhost pelo xamp, mais da erro 104 pode me ajudar?

**Comment by Ironaldo-Silva** [comment]
![captura de tela 1](https://cloud.githubusercontent.com/assets/26805772/25772718/4b004a8a-3247-11e7-9b23-ca1ede79f876.png)

**Comment by Ironaldo-Silva** [comment]
essa parte já consegui

**Comment by rafaelmarques** [comment]
Tem muita coisa personalizada. Como fiz para meu cenário não me preocupei em deixar algo para uma instalação automática. Vou mandar upgrades por funções.
