### ISSUE TITLE
Erros encontrados nas abas clientes; ordem de servisos e financeiro varias abas

### ISSUE THREAD

**Issue by Ironaldo-Silva** [rafaelmarques/os#2]
essas paginas todas de erro:
![captura de tela 3](https://cloud.githubusercontent.com/assets/26805772/25772887/868ec402-324a-11e7-9e66-f7affc489b3c.png)
![captura de tela 4](https://cloud.githubusercontent.com/assets/26805772/25772892/86a91500-324a-11e7-8f8e-7e8be6391d0f.png)
![captura de tela 5](https://cloud.githubusercontent.com/assets/26805772/25772889/86907392-324a-11e7-92c5-670d4399428d.png)
![captura de tela 6](https://cloud.githubusercontent.com/assets/26805772/25772891/8693f774-324a-11e7-9f2b-61031406a0aa.png)
![captura de tela 7](https://cloud.githubusercontent.com/assets/26805772/25772893/86be6be4-324a-11e7-8580-035e286dcfee.png)
![captura de tela 8](https://cloud.githubusercontent.com/assets/26805772/25772890/869098ea-324a-11e7-977a-1ffcaa0b0e60.png)
![captura de tela 9](https://cloud.githubusercontent.com/assets/26805772/25772888/868f935a-324a-11e7-9bb5-b1096a1460d5.png)
![captura de tela 10](https://cloud.githubusercontent.com/assets/26805772/25772894/8720b196-324a-11e7-9393-de3953085e99.png)

**Comment by rafaelmarques** [comment]
Meu banco de dados tem tabelas e campos novos. Não vai funcionar com o db original. Vou mandar por partes. Use o sistema original e siga implementando as funções conforme eu for mandando.

Em anexo tem as instruções para implementar o Dashboard com o calendário. Por não ter alteração de DB fica mais simples.

[MapOS-Calendar.zip](https://github.com/rafaelmarques/os/files/998302/MapOS-Calendar.zip)
